"""Filesystem layout.

One place that knows where things live, so no module has to guess. All paths
are relative to the repo root unless ``REVAL_HOME`` overrides it, which is what
CI and tmp-dir tests use.
"""

from __future__ import annotations

import os
from pathlib import Path


def repo_root() -> Path:
    """Repo root: ``REVAL_HOME`` if set, else the package's grandparent."""
    env = os.environ.get("REVAL_HOME")
    if env:
        return Path(env).expanduser().resolve()
    # src/reval/paths.py -> src/reval -> src -> root
    return Path(__file__).resolve().parents[2]


def data_dir() -> Path:
    """Downloaded corpora. Gitignored; rebuilt by ``reval corpus download``."""
    return _ensure(repo_root() / "data")


def cache_dir() -> Path:
    """Content-addressed embedding cache. Gitignored; safe to delete."""
    return _ensure(repo_root() / "cache")


def runs_dir() -> Path:
    """TREC-format run files. Gitignored; regenerated by ``reval run``."""
    return _ensure(repo_root() / "runs")


def results_dir() -> Path:
    """Parquet tables, manifests, and plots."""
    return _ensure(repo_root() / "results")


def index_dir() -> Path:
    """On-disk retrieval indexes (embedded Qdrant, serialized BM25)."""
    return _ensure(repo_root() / "data" / "indexes")


def configs_dir() -> Path:
    return repo_root() / "configs"


def prompts_dir() -> Path:
    return repo_root() / "prompts"


def _ensure(p: Path) -> Path:
    p.mkdir(parents=True, exist_ok=True)
    return p
