"""BM25 sparse retrieval, via ``bm25s``.

PLAN.md §1 is blunt about why this is here: BM25 beats dense retrievers on
several BEIR datasets, and a dense-only benchmark with no sparse baseline is not
credible. It is also the retriever most likely to expose eval-set contamination,
because a query generated by paraphrasing a passage shares that passage's
vocabulary — which is exactly what BM25 scores.

Stemming is on by default (Porter, via PyStemmer) because BEIR's published BM25
numbers come from Anserini with stemming enabled. Turning it off would hand the
dense retrievers a few points of unearned margin.
"""

from __future__ import annotations

from collections.abc import Sequence

import bm25s

from reval.indexing.base import IndexNotBuiltError
from reval.types import Chunk, Queries, Run


class BM25Retriever:
    """Lexical baseline over chunk text."""

    def __init__(
        self,
        k1: float = 0.9,
        b: float = 0.4,
        method: str = "lucene",
        stopwords: str = "en",
        stemmer: str | None = "english",
        name: str = "bm25",
    ):
        # k1=0.9, b=0.4 are Anserini's BEIR defaults, not bm25s's (1.5/0.75).
        # Using the library default would make our BM25 quietly different from
        # every published BEIR BM25 number.
        self.k1 = k1
        self.b = b
        self.method = method
        self.stopwords = stopwords
        self.stemmer_name = stemmer
        self.name = name

        self._retriever: bm25s.BM25 | None = None
        self._chunk_ids: list[str] = []
        self._stemmer = self._make_stemmer(stemmer)

    @staticmethod
    def _make_stemmer(name: str | None):
        if not name:
            return None
        try:
            import Stemmer
        except ImportError:  # pragma: no cover - PyStemmer is a core dep
            return None
        return Stemmer.Stemmer(name)

    def config(self) -> dict[str, object]:
        return {
            "k1": self.k1,
            "b": self.b,
            "method": self.method,
            "stopwords": self.stopwords,
            "stemmer": self.stemmer_name,
        }

    def index(self, chunks: Sequence[Chunk]) -> None:
        if not chunks:
            raise ValueError("cannot index an empty chunk list")
        self._chunk_ids = [c.chunk_id for c in chunks]
        tokens = bm25s.tokenize(
            [c.text for c in chunks],
            stopwords=self.stopwords,
            stemmer=self._stemmer,
            show_progress=False,
        )
        retriever = bm25s.BM25(method=self.method, k1=self.k1, b=self.b)
        retriever.index(tokens, show_progress=False)
        self._retriever = retriever

    def search(self, queries: Queries, top_k: int) -> Run:
        if self._retriever is None:
            raise IndexNotBuiltError("call index() before search()")
        if not queries:
            return {}

        # bm25s raises if k exceeds the corpus size rather than returning what
        # it has. Clamping here keeps small-corpus tests and smoke runs working.
        k = min(top_k, len(self._chunk_ids))

        qids = sorted(queries)
        query_tokens = bm25s.tokenize(
            [queries[q] for q in qids],
            stopwords=self.stopwords,
            stemmer=self._stemmer,
            show_progress=False,
        )
        indices, scores = self._retriever.retrieve(query_tokens, k=k, show_progress=False)

        run: Run = {}
        for row, qid in enumerate(qids):
            hits: dict[str, float] = {}
            for col in range(indices.shape[1]):
                score = float(scores[row, col])
                # A zero score means no query term matched. Keeping it would pad
                # the run with arbitrary documents whose only claim to rank is
                # tie-breaking on doc id.
                if score <= 0.0:
                    continue
                hits[self._chunk_ids[int(indices[row, col])]] = score
            run[qid] = hits
        return run
